from telegram import Update
from telegram.ext import ContextTypes

from nanoclaw_bot.security import owner_only


@owner_only
async def help_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Detailed help for all commands."""
    await update.message.reply_text(
        "🦎 *NanoClaw Bot — Command Reference*\n\n"
        "*🚀 /start*\n"
        "Show welcome message and quick-start guide.\n\n"
        "*🔑 /configure KEY=value ...*\n"
        "Set one or more API keys. Keys must be UPPER\\_SNAKE\\_CASE.\n"
        "Example: `/configure OPENAI_API_KEY=sk-abc123`\n"
        "Multiple: `/configure OPENAI_API_KEY=sk-... MISTRAL_API_KEY=xm-...`\n\n"
        "*🔐 /keys*\n"
        "View all configured API keys with masked values.\n"
        "Only the last 4 characters are shown.\n\n"
        "*📊 /status*\n"
        "Show bot version, Python version, platform (Termux/Linux),\n"
        "uptime, and number of configured API keys.\n\n"
        "*🤖 /agents [subcommand]*\n"
        "Manage AI agent processes in tmux sessions.\n"
        "• `/agents` — List running sessions\n"
        "• `/agents start <name> <cmd>` — Start agent\n"
        "• `/agents stop <name>` — Stop agent\n"
        "• `/agents restart <name> <cmd>` — Restart agent\n"
        "• `/agents logs <name>` — View agent output\n\n"
        "*💻 /shell <command>*\n"
        "Execute a shell command remotely (30s timeout).\n"
        "Example: `/shell ls -la`\n"
        "Example: `/shell df -h`\n"
        "⚠️ Dangerous commands (rm -rf /, shutdown, etc.) are blocked.\n\n"
        "*🧬 /eliza [subcommand]*\n"
        "AI personality engine with conversation memory.\n"
        "• `/eliza` — Show current personality\n"
        "• `/eliza set <mode>` — Switch personality\n"
        "  Modes: assistant, therapist, creative, technical\n"
        "• `/eliza list` — List all personalities\n"
        "• `/eliza clear` — Clear conversation memory\n"
        "• `/eliza <prompt>` — Enhance prompt with personality context\n\n"
        "*📋 /logs [N]*\n"
        "View last N lines of bot log (default: 30, max: 100).\n"
        "Example: `/logs` or `/logs 50`\n\n"
        "*🔔 /notify [subcommand]*\n"
        "Monitor agent sessions and get crash alerts.\n"
        "• `/notify on` — Enable monitoring\n"
        "• `/notify off` — Disable monitoring\n"
        "• `/notify status` — Show monitoring status\n"
        "• `/notify autorestart on|off` — Toggle auto-restart\n\n"
        "*🔄 /update*\n"
        "Pull latest code from GitHub, reinstall dependencies,\n"
        "and restart the bot. Reports progress via Telegram.\n"
        "Skips restart if already up to date.\n\n"
        "*📦 /backup*\n"
        "Export bot configuration as a JSON file.\n"
        "Includes key names, agent list, and settings (no secrets).\n\n"
        "*❓ /help*\n"
        "Show this help message.\n\n"
        "*Security:*\n"
        "All commands are restricted to the configured owner chat ID.\n"
        "API keys are stored in a `.env` file with 0600 permissions.",
        parse_mode="Markdown",
    )
